name: Create/destroy ECS (WordPress + RDS MySQL)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the Terraform action to perform'
        required: true
        default: 'step1'
        type: choice
        options:
          - 'step1'
          - 'step3'
          - 'destroy'

jobs:
  process-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Set initial Terraform status
        run: echo "TERRAFORM_STATUS=❌ Failed" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Init Terraform (step1)
        if: contains(github.event.inputs.action, 'step1')
        run: terraform init
        working-directory: step1

      - name: Plan Terraform (step1)
        if: contains(github.event.inputs.action, 'step1')
        run: terraform plan
        working-directory: step1

      - name: Apply Terraform (step1)
        if: contains(github.event.inputs.action, 'step1')
        id: apply_step1
        run: terraform apply -auto-approve
        working-directory: step1

      - name: Collect status (step1)
        if: contains(github.event.inputs.action, 'step1')
        id: collect_status_apply_step1
        run: |
          echo "CREATED_VPC_ID=$(terraform output created_vpc_id)" >> $GITHUB_ENV
          echo "PUBLIC_SUBNET_ID_1=$(terraform output public_subnet_id_1)" >> $GITHUB_ENV
          echo "PUBLIC_SUBNET_ID_2=$(terraform output public_subnet_id_2)" >> $GITHUB_ENV
          echo "PRIVATE_SUBNET_ID_1=$(terraform output private_subnet_id_1)" >> $GITHUB_ENV
          echo "PRIVATE_SUBNET_ID_2=$(terraform output private_subnet_id_2)" >> $GITHUB_ENV
          echo "RDS_DB_ENDPOINT=$(terraform output rds_endpoint)" >> $GITHUB_ENV
          echo "TERRAFORM_STATUS=$([[ '${{ steps.apply_step1.outcome }}' == 'success' ]] && echo '✅ Success')" >> $GITHUB_ENV

      - name: Send Telegram Notification (step1)
        if: contains(github.event.inputs.action, 'step1')
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *Create infrastructure (VPC + Subnets + Route tables + RDS DB Results (step1)*:
            *VPC Id*: ${{ env.CREATED_VPC_ID }}
            *Public Subnet Id 1*: ${{ env.PUBLIC_SUBNET_ID_1 }}
            *Public Subnet Id 2*: ${{ env.PUBLIC_SUBNET_ID_2 }}
            *Private Subnet Id 1*: ${{ env.PRIVATE_SUBNET_ID_1 }}
            *Private Subnet Id 2*: ${{ env.PRIVATE_SUBNET_ID_2 }}
            *RDS Endpoint Id*: ${{ env.RDS_DB_ENDPOINT }}
            *Terraform Apply Status*: ${{ env.TERRAFORM_STATUS }}

      - name: Init Terraform (step3)
        if: contains(github.event.inputs.action, 'step3')
        run: terraform init
        working-directory: step3

      - name: Plan Terraform (step3)
        if: contains(github.event.inputs.action, 'step3')
        run: terraform plan
        working-directory: step3

      - name: Apply Terraform (step3)
        if: contains(github.event.inputs.action, 'step3')
        id: apply_step3
        run: terraform apply -chdir=step3 -auto-approve
        working-directory: step3

      - name: Collect status (step3)
        if: contains(github.event.inputs.action, 'step3')
        id: collect_status_apply_step3
        run: |
          echo "CREATED_ALB_DNS_NAME=$(terraform output alb_dns_name)" >> $GITHUB_ENV
          echo "TERRAFORM_STATUS=$([[ '${{ steps.apply_step3.outcome }}' == 'success' ]] && echo '✅ Success')" >> $GITHUB_ENV

      - name: Send Telegram Notification (step3)
        if: contains(github.event.inputs.action, 'step3')
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *Create ECS infrastructure (step3)*:
            *Created ALB DNS Name*: ${{ env.CREATED_ALB_DNS_NAME }}
            *Terraform Apply Status*: ${{ env.TERRAFORM_STATUS }}

      - name: Destroy Terraform (destroy)
        if: contains(github.event.inputs.action, 'destroy')
        id: destroy
        run: terraform destroy -auto-approve

      - name: Collect status (destroy)
        if: contains(github.event.inputs.action, 'destroy')
        id: collect_status_destroy
        run: |
          echo "TERRAFORM_STATUS=$([[ '${{ steps.destroy.outcome }}' == 'success' ]] && echo '✅ Success')" >> $GITHUB_ENV

      - name: Send Telegram Notification (destroy)
        if: contains(github.event.inputs.action, 'destroy')
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *Destroy ECS infrastructure Result*:
            *Terraform Destroy Status*: ${{ env.TERRAFORM_STATUS }}
