name: Create/destroy ECS (WordPress + RDS MySQL)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the Terraform action to perform'
        required: true
        default: 'create'
        type: choice
        options:
          - 'create'
          - 'destroy'

env:
  AWS_REGION: "eu-central-1"
  ECR_REPOSITORY: "wordpress-repo"
  IMAGE_TAG: "custom"

jobs:
  ECS:
    runs-on: ubuntu-latest

    steps:
      - name: Set initial Terraform status
        run: |
          echo "STEP1_TERRAFORM_STATUS=❌ Failed" >> $GITHUB_ENV
          echo "DOCKER_BUILD_STATUS=❌ Failed" >> $GITHUB_ENV
          echo "DOCKER_PUSH_STATUS=❌ Failed" >> $GITHUB_ENV
          echo "ECR_IMAGE_REMOVE_STATUS=❌ Failed" >> $GITHUB_ENV
          echo "STEP3_TERRAFORM_STATUS=❌ Failed" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Init Terraform (step3)
        if: contains(github.event.inputs.action, 'create')
        run: terraform init
        working-directory: step3

      - name: Plan Terraform (step3)
        if: contains(github.event.inputs.action, 'create')
        run: terraform plan \
             -var 'ecr_image_uri="571600859313.dkr.ecr.eu-central-1.amazonaws.com/wordpress-repo:custom"' \
             -var 'vpc_id="vpc-032203c3f2faff8e9"' \
             -var 'public_subnet_id_1="subnet-043ab186a0d3d8362"' \
             -var 'public_subnet_id_2="subnet-0b8179873aa25b744"' \
             -var 'private_subnet_id_1="subnet-0eb99e19d155f09c8"' \
             -var 'private_subnet_id_2="subnet-0d05137f7b4e2434f"'
        working-directory: step3
